### ISSUE TITLE
Jao_Afa第4世代の累計ログイン時間がおかしい

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb-users#308]
### 不具合の説明

ユーザーデータ画面にある、Jao_Afa第4世代の累計ログイン時間表記がおかしい

### 再現手順

1. [`kohonayoshi`のユーザーデータ画面](https://users.jaoafa.com/26728d53-add7-46d1-97c3-0a25bc6607f5) に移動する
2. `ユーザー情報`→`累計ログイン時間`→`詳細を見る` をクリックする
3. 第4世代の累計ログイン時間がおかしい！

### スクリーンショット

![image](https://user-images.githubusercontent.com/52349485/158762655-5eec09ef-34c8-4c03-87a2-5aa41c8ee6fc.png)

**Comment by book000** [comment]
修正しました(バックエンドシステム + 過去オンラインタイムのデータベース内容)。[jaopediaの記事内容](https://wiki.jaoafa.com/jao_Minecraft_Server#.E6.AD.B4.E5.8F.B2)に則り、1.18.1以降のオンライン時間を第4世代として扱うように変更しました。
