### ISSUE TITLE
ユーザーページ内、Discordのアイコンの表示がおかしい

### ISSUE THREAD

**Issue by minhero-exp** [jaoafa/jaoweb-users#426]
![image](https://user-images.githubusercontent.com/75877469/180988355-c91ace23-b124-49c4-9aa9-62868e759402.png)

環境は Windows11 の Google Chrome（103.0.5060.134）です。

**Comment by book000** [comment]
めも: 該当ツイートツリー https://twitter.com/book000/status/1551877592893952001

**Comment by book000** [comment]
#426で修正
