### ISSUE TITLE
時間部分の表記ミス

### ISSUE THREAD

**Issue by jaotan** [jaoafa/jaoweb-users#44]
## Contents
```
時間部分の表記ミス

累計ログイン時間の表示が不思議なことになっている
https://gyazo.com/78a585c489e3ba88bbcea990d7bc4ec5
(分のところが時間になっている...？)
```
## Message URL
https://discord.com/channels/597378876556967936/626727474922913792/824406493704224768

**Comment by book000** [comment]
併せて、
usersのグループ情報日時が不明になることがある(これが再現するのはdefaultのみ)
なので、groupWhenがnullの時に表示しないようにする
