### ISSUE TITLE
1日？1週間？月？あたりのログイン時間を表示してほしい

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb-users#60]
![image](https://user-images.githubusercontent.com/52349485/114956649-48e43680-9e9a-11eb-8255-e99cd4dbb238.png)
ログイン時間、いまいちピンとこないので1日？1週間？月？あたりのログイン時間を既存のログイン時間の後ろに括弧書きかなにかで表示してほしい
1日だとすごく短くなるし実感的じゃないから1週間あたりの方がいいと思う

**Comment by kohonayoshi** [comment]
わかる

**Comment by book000** [comment]
`54日14時間37分14秒 (約7.71週間)` のような？

**Comment by kohonayoshi** [comment]
ごめん言い方悪かった
54日14時間37分14秒 (8時間32分17秒/週あたり)
※鯖稼働時間/ログイン時間
のような。

**Comment by book000** [comment]
鯖稼働時間を取れるかどうかが難しいかもしれん。週あたりの稼働時間なんて統計取ってなかったし…

**Comment by kohonayoshi** [comment]
いや週あたりの稼働時間じゃなくてもシンプルに鯖稼働時間を/7すればいい
鯖稼働時間が取れるかどうかはべつとして

**Comment by book000** [comment]
むむむ、考えます。やるとしても土日

**Comment by kohonayoshi** [comment]
まったくもっていそがない

**Comment by book000** [comment]
鯖の稼働時間を取得する手段がない(ワールドの動作時間と思ったけどうまくいかなかった)ので、実装不能として処理します。

**Comment by kohonayoshi** [comment]
(◞‸◟)
