### ISSUE TITLE
Least loginの値がおかしい

### ISSUE THREAD

**Issue by kohonayoshi** [jaoafa/jaoweb-users#61]
![image](https://user-images.githubusercontent.com/52349485/114957534-37039300-9e9c-11eb-8b50-48d6a5cc33ec.png)
何日前のとこの計算がなんかおかしい気がする

**Comment by book000** [comment]
…？
何もおかしくないと思うんだけど…

**Comment by book000** [comment]
応答がない。 @kohonayoshi

**Comment by kohonayoshi** [comment]
.

**Comment by kohonayoshi** [comment]
![image](https://user-images.githubusercontent.com/52349485/115101348-6b4f8000-9f7e-11eb-8084-022a6f5b1425.png)
https://users.jaoafa.com/OnShitsu
もっとわかりやすくなってたのでラッキー

**Comment by book000** [comment]
うえ～なんでだ。あとで見ます

**Comment by book000** [comment]
めも: https://github.com/jaoafa/jaoapi-v2/blob/a1dc1fa7cc853caff173f99755a6f65bd5ea13d3/src/users_router.py#L61

**Comment by kohonayoshi** [comment]
補足
・1.16.5以降(4/2～)にログインしたユーザーで発生
・0～7日で推移している？(曜日で集計されているかもしれない？)

**Comment by book000** [comment]
原因: 年月を計算していない（日のみ返している影響で、日数ではなくなっている）
